apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
  labels:
    app: reddit-clone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0    
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: reddit-clone-app
    spec:
      containers:
        - name: reddit-clone-app
          image: dineth123412/reddit-clone-app:1.0.0-15
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
